[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fmbf"
version = "1.2"
authors = [
  { name="Fork Genesis", email="vasyapinfo@ya.ru" },
]
description = "Fork's Minecraft Botting Framework"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/vpgel/fmbf"
Issues = "https://github.com/vpgel/fmbf/issues"